### ISSUE TITLE
Implement some other new super-feature

### ISSUE THREAD

**Issue by satano** [Kros-sk/ContributingDemo#2]
Maecenas ac dictum mi, eu malesuada purus. Phasellus eu metus sit amet ipsum pharetra suscipit sed ac nunc. Pellentesque et purus orci. Vestibulum sit amet euismod justo. In tempus dapibus est eget hendrerit. Maecenas et enim eget dui blandit placerat. Nunc pellentesque iaculis nunc eu imperdiet. Vivamus et dui elit.

**Comment by satano** [comment]
Rád by som spravil toto.

**Comment by Burgyn** [comment]
Jasné, nech sa páči. DIk
